lib/icyboard_web/router.ex
defmodule IcyboardWeb.Router do
  use IcyboardWeb, :router

  import IcyboardWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {IcyboardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IcyboardWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  ## Live dashboard and Swoosh mailbox (dev only)

  if Mix.env() == :dev do
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/live_dashboard", metrics: IcyboardWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", IcyboardWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", IcyboardWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/dashboard", DashboardLive, :index
    live "/projects", ProjectLive.Index, :index
    live "/project/new", ProjectLive.New, :new
    live "/project/:code", ProjectLive.Show, :show
    live "/project/:code/add", ProjectLive.Show, :add
    live "/item/:code", ItemLive.Show, :show
    live "/item/:code/add", ItemLive.Show, :add
    live "/item/:code/edit", ItemLive.Show, :edit
    live "/item/:code/clone", ItemLive.Show, :clone
    live "/item/:code/delete", ItemLive.Show, :delete
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", IcyboardWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/icyboard_web/views/layout_view.ex
defmodule IcyboardWeb.LayoutView do
  use IcyboardWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/icyboard_web/templates/layout/_menu.html.heex
<nav class="navbar is-info" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <div class="navbar-item">
            <span class="icon is-small">
                <i class="fa-solid fa-snowflake" aria-hidden="true"></i>
                &nbsp;
            </span>
            <span>
                Icyboard
            </span>
        </div>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navMain">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navMain" class="navbar-menu">
        <div class="navbar-start">
            <%= if @current_user do %>
                <%= live_redirect to: Routes.dashboard_path(@conn, :index), class: "navbar-item" do %>
                    Dashboard
                <% end %>
                <%= live_redirect to: Routes.project_index_path(@conn, :index), class: "navbar-item" do %>
                    Projects
                <% end %>
                <a class="navbar-item">
                    Time
                </a>
                <a class="navbar-item">
                    Boards
                </a>
            <% end %>
        </div>
        <div class="navbar-end">
            <%= if @current_user do %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        <%= if @current_user.display_name, do: @current_user.display_name, else: @current_user.email %>
                    </a>

                    <div class="navbar-dropdown">
                        <%= if @current_user.display_name do %>
                            <div class="navbar-item"><%= @current_user.email %></div>
                        <% end %>
                        <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "navbar-item" %>
                        <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% else %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link to: Routes.user_registration_path(@conn, :new), class: "button is-primary" do %>
                            <strong>Sign up</strong>
                        <% end %>
                        <%= link to: Routes.user_session_path(@conn, :new), class: "button is-light" do %>
                            Log in
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</nav>

lib/icyboard_web/templates/layout/app.html.heex
<main class="container">
  <%= if get_flash(@conn, :info) do %>
    <div class="flash message is-info">
      <div class="message-body">
        <%= get_flash(@conn, :info) %>
      </div>
    </div>
  <% end %>

  <%= if get_flash(@conn, :success) do %>
    <div class="flash message is-success">
      <div class="message-body">
        <%= get_flash(@conn, :success) %>
      </div>
    </div>
  <% end %>

  <%= if get_flash(@conn, :error) do %>
    <div class="flash message is-danger">
      <div class="message-body">
        <%= get_flash(@conn, :error) %>
      </div>
    </div>
  <% end %>

  <%= @inner_content %>
</main>

lib/icyboard_web/templates/layout/live.html.heex
<main class="container">
  <% info = live_flash(@flash, :info) %>
  <%= if info do %>
    <div class="flash message is-info" phx-click="lv:clear-flash" phx-value-key="info">
      <div class="message-body">
        <%= info %>
      </div>
    </div>
  <% end %>

  <% success = live_flash(@flash, :success) %>
  <%= if success do %>
    <div class="flash message is-success" phx-click="lv:clear-flash" phx-value-key="success">
      <div class="message-body">
        <%= success %>
      </div>
    </div>
  <% end %>

  <% error = live_flash(@flash, :error) %>
  <%= if error do %>
    <div class="flash message is-danger" phx-click="lv:clear-flash" phx-value-key="error">
      <div class="message-body">
        <%= error %>
      </div>
    </div>
  <% end %>

  <%= @inner_content %>
</main>

lib/icyboard_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Icyboard", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <%= render "_menu.html", assigns %>
    </header>
    <%= @inner_content %>
  </body>
</html>