lib/icyboard_web/router.ex
defmodule IcyboardWeb.Router do
  use IcyboardWeb, :router

  import IcyboardWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {IcyboardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IcyboardWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  ## Live dashboard and Swoosh mailbox (dev only)

  if Mix.env() == :dev do
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/live_dashboard", metrics: IcyboardWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", IcyboardWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", IcyboardWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/dashboard", DashboardLive, :index
    live "/projects", ProjectLive.Index, :index
    live "/project/new", ProjectLive.New, :new
    live "/project/:code", ProjectLive.Show, :show
    live "/project/:code/add", ProjectLive.Show, :add
    live "/item/:code", ItemLive.Show, :show
    live "/item/:code/add", ItemLive.Show, :add
    live "/item/:code/edit", ItemLive.Show, :edit
    live "/item/:code/clone", ItemLive.Show, :clone
    live "/item/:code/delete", ItemLive.Show, :delete
    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", IcyboardWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/icyboard_web/controllers/user_registration_controller.ex
defmodule IcyboardWeb.UserRegistrationController do
  use IcyboardWeb, :controller

  alias Icyboard.Accounts
  alias Icyboard.Accounts.User
  alias IcyboardWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/icyboard_web/views/user_registration_view.ex
defmodule IcyboardWeb.UserRegistrationView do
  use IcyboardWeb, :view
end

lib/icyboard_web/templates/user_registration/new.html.heex
<div class="page-title">
  <h1>Register</h1>
</div>

<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :email, class: "label" %>
    <p class="control has-icons-left">
      <%= email_input f, :email, required: true, class: "input" %>
      <span class="icon is-small is-left">
        <i class="fa-solid fa-user"></i>
      </span>
    </p>
    <%= error_tag f, :email %>
  </div>

  <div class="field">
    <%= label f, :password, class: "label" %>
    <p class="control has-icons-left">
      <%= password_input f, :password, required: true, class: "input" %>
      <span class="icon is-small is-left">
        <i class="fa-solid fa-key"></i>
      </span>
    </p>
    <%= error_tag f, :password %>
  </div>

  <div class="field">
    <%= submit class: "button is-success" do %>
      <span class="icon is-small">
        <i class="fa-solid fa-right-to-bracket"></i>
      </span>
      <span>
        Register
      </span>
    <% end %>
  </div>
</.form>

<p>
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %> |
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
</p>